- name: Sitemap Generator
  # You may pin to the exact commit or the version.
  # uses: cgs-earth/sitemap-generator@bc8302d4348162e6ed421f51d4a6c51c61ddc615
  uses: cgs-earth/sitemap-generator@0.2.1
  with:
    # Filepath to load data from
    namespace_dir: # default is ./namespaces
    # Directory for sitemap output
    sitemap_dir: # default is ./sitemap
    # Source repository
    source_repo: # default is geoconnex.us
    # Filepath to git lastmod from
    source_repo_path: # default is namespaces
